esphome:
  name: esp-voice
  friendly_name: ESPVoice
  min_version: 2024.11.0
  name_add_mac_suffix: false

#   enable amplifier
  on_boot:
    then:
      - switch.turn_on: gpio_amp

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

external_components:
  source:
    type: git
    url: https://github.com/woeiwen/esphome-components.git
    ref: main
  components: [ac101]
  refresh: 1s

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome
  password: "d0bf1c3eb9477afde204e9c8067e7473"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

substitutions:
#  friendly_name: ESPVoice
  # Audiokit Buttons
  KEY1: "36"
  KEY2: "13" # may be in use for other purposes, see onboard config switch
  KEY3: "19" # also activates LED D4 if pressed
  KEY4: "23" # do not use on A1S V2.3 with initial pinout -> I2C ES8388
  KEY5: "18" # do not use on A1S V2.3 with initial pinout -> I2C ES8388
  KEY6: "5"  # do not use on A1S V2.3 with initial pinout -> I2S
  # Audiokit LEDs
  LED_D4: "22"
  LED_D5: ${KEY3}

status_led:
  pin:
    number: ${LED_D4}
    inverted: true
    allow_other_uses: true

# buttons
binary_sensor:
  - platform: gpio
    pin:
      number: ${KEY2}
      inverted: true
      mode: INPUT_PULLUP
    name: Volume Down
    on_click:
      - media_player.volume_down:
          id: media_out
  - platform: gpio
    pin:
      number: ${KEY3}
      inverted: true
      mode: INPUT_PULLUP
      allow_other_uses: true
    name: Volume Up
    on_click:
      - media_player.volume_up:
          id: media_out
  - platform: gpio
    pin:
      number: ${KEY4}
      inverted: true
      mode: INPUT_PULLUP
    name: Voice Assistant
    id: echo_button
    on_press:
      - voice_assistant.start:
    on_release:
      - voice_assistant.stop:
    on_click:
      - media_player.toggle:
          id: media_out
  - platform: gpio
    pin:
     number: ${KEY5}
     inverted: true
     mode: INPUT_PULLUP
    name: Web Radio
    on_click:
      - media_player.play_media: 'http://100radio-tarbes.ice.infomaniak.ch/100radio-tarbes-128.mp3'
  - platform: gpio
    pin:
     number: ${KEY6}
     inverted: true
     mode: INPUT_PULLUP
    name: Voice+
    on_click:
      - if:
          condition: voice_assistant.is_running
          then:
            - voice_assistant.stop:
          else:
            - voice_assistant.start_continuous:

  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
      mode:
        input: true
    name: "Jack Status"

# voice assistant
voice_assistant:
  microphone: mic_id
  speaker: announcment_spk_id

# I2S Audio
i2s_audio:
  i2s_lrclk_pin: 26
  i2s_bclk_pin: 27

microphone:
  - platform: i2s_audio
    adc_type: external
    i2s_din_pin: 35
    pdm: false
    id: mic_id
    bits_per_sample: 16bit

media_player:
  - platform: speaker
    name: "EspVoice Media Player"
    id: media_out
    announcement_pipeline:
      speaker: announcment_spk_id

speaker:
  - platform: i2s_audio
    id: announcment_spk_id
    dac_type: external
    i2s_dout_pin: 
      number: 25
    sample_rate: 44100
    bits_per_sample: 16bit
    channel: stereo


# AC101 (I2C)
i2c:
  sda: 33
  scl: 32
  scan: true

ac101:
  # address: 0x1a

# Amplifier
switch:
  - platform: gpio
    pin: 21
    name: "AMP Switch"
    id: gpio_amp
    restore_mode: ALWAYS_ON
  - platform: restart
    name: "EspVoice Restart"

light:
  - platform: binary
    name: "Test LED 1"
    output: light_output_1
  - platform: binary
    name: "Test LED 2"
    output: light_output_2

output:
  - id: light_output_1
    platform: gpio
    pin:
      number: ${LED_D4}
      inverted: true
      allow_other_uses: true
  - id: light_output_2
    platform: gpio
    pin:
      number: ${LED_D5}
      inverted: true
      allow_other_uses: true
